spring.application.name=DTO
spring.datasource.url=jdbc:postgresql://localhost:5432/EMPLEADOS
spring.datasource.username=LUISM
spring.datasource.password=LUISM
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8082
