CREATE TABLE EMPLEADO (
    ID SERIAL PRIMARY KEY,
    CEDULA VARCHAR(13),
    NOMBRES VARCHAR(100),
    APELLIDOS VARCHAR(100),
    SUELDO NUMERIC(10, 2),
	ESTADO VARCHAR(1),
    USUARIO_CREACION INTEGER,
    FECHA_CREACION TIMESTAMP,
    USUARIO_MODIFICACION INTEGER,
    FECHA_MODIFICACION TIMESTAMP
);